version: "3.8"

# volumes:
#   rabbitmq_data:

services:
 
  ###################################
  # Booking: The Booking microservice
  ###################################
  booking:
    build:
      context: ./
      dockerfile: booking.Dockerfile
    image: smuozj/booking:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3308/tourdb
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
 
 
  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
   
  #################################################
  # Activity Log: The Activity Log microservice
  #################################################
  activity_log:
    build:
      context: ./
      dockerfile: activity_log.Dockerfile
    image: ozjsmu/activity_log:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################

  error:
    build:
      context: ./
      dockerfile: error.Dockerfile
    image: ozjsmu/error:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # Place booking: The Place Booking microservice
  ###############################################
  place_booking:
    build:
      context: ./
      dockerfile: place_booking.Dockerfile
    image: smuozj/place_booking:esd
    restart: always
    depends_on:
      - booking
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      booking_URL: http://localhost:5001/booking
      PYTHONUNBUFFERED: 1
    ports:
      - "5101:5100"
    env_file:
      - .env

  ##################################
  # Tour: The Tour microservice
  ##################################
  tour:
    build:
      context: ./
      dockerfile: tour.Dockerfile
    image: smuozj/tour:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3308/tourdb
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
    env_file:
      - .env


#rebuild the containers using docker-compose up --build command.
